<a href="https://colab.research.google.com/github/rumanakuraishiya/Rumana/blob/main/practice_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

marks = np.array([
    [90,80,85],
    [90,99,89]

])
print(marks)

[[90 80 85]
 [90 99 89]]


In [ ]:
import numpy as np

marks = np.array([10,20,30,40])

print(marks)

[10 20 30 40]


In [ ]:
import numpy as np

student = np.array([
    [80,90],
    [60,70],
    [50,90]
])
print(student)

[[80 90]
 [60 70]
 [50 90]]


In [ ]:
import numpy as np
arr = np.zeros((2,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
def attendance(attended,total):
       return(attended/total)*100

attended = int(input("classes attended: "))
total = int(input("total classes: "))

percentage = attendance(attended,total)

print("attendance precentage =",round(percentage,2),"%")

classes attended: 60
total classes: 50
attendance precentage = 120.0 %


In [ ]:
def calculate_average(x,y,z):
    return (x+y+z)/3
try:
    x = int(input("Enter first number:"))
    y = int(input("Enter second number:"))
    z = int(input("Enter third number:"))
    print("calculator_average =",calculate_average(x,y,z))
except ValueError:
    print("Invalid Input")

Enter first number:30
Enter second number:40
Enter third number:60
calculator_average = 43.333333333333336


In [ ]:
import numpy as np

arr = np.array([1,2,3,4,5,6])

new_arr = arr.reshape(2,3)

print(new_arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
marks=np.array([70,80,90,94,86])
average=np.mean(marks)
print(average)

84.0


In [ ]:
marks = np.array([60,70,80,90,78])
average = np.median(marks)
print(average)

78.0


In [ ]:
salary = np.array([10000,20000,25000,30000])
med = np.mean(salary)
print(med)

21250.0


In [ ]:
sales=[10000,15000,20000,25000]

total=sum(sales)
avg=total/len(sales)
high_sales=max(sales)
low_sales=min(sales)

print("total:",total)
print("average:",high_sales)
print("low_sales:",low_sales)

total: 70000
average: 25000
low_sales: 10000


In [ ]:
import pandas as pd

data = pd.Series([20,30,40,50])

print(data)

0    20
1    30
2    40
3    50
dtype: int64


In [ ]:
data = pd.Series(
    [100,200,300],
    index=["A","B","C"]
)

print(data)

A    100
B    200
C    300
dtype: int64


In [ ]:
data={
    "Name":["Ram","Sita"],
    "Age":[25,30],
    "Dpartment":["HR","IT"]

}
df=pd.DataFrame(data)
print(df)

   Name  Age Dpartment
0   Ram   25        HR
1  Sita   30        IT


In [ ]:
import numpy as np
product = ["laptop","mobile","tab","watch"]

sales= np.array([100,400,500,700])

print("total sales:", np.sum(sales))
print("average sales:", np.mean(sales))
print("highest sales:", np.max(sales))
print("lowest sales:",np.min(sales))

total sales: 1700
average sales: 425.0
highest sales: 700
lowest sales: 100
